apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp-deployment
  labels:
    app: nodejsapp
    release: prometheus
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
        release: prometheus
    spec:
      containers:
        - name: nodeserver
          image: jasonbeh19/nodejsapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3004
            - containerPort: 3005
          env:
            - name: MONGODB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: nodejsapp-secret
                  key: mongodb_connection_string
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: nodejsapp-secret
                  key: auth0_domain
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: nodejsapp-secret
                  key: auth0_client_id
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: nodejsapp-secret
                  key: auth0_client_secret
            - name: AUTH0_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: nodejsapp-secret
                  key: auth0_callback_url
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: nodejsapp-secret
                  key: session_secret
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: nodejsapp-secret
                  key: cookie_secret
            - name: PORT
              value: "3004"
