apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: app
type: Opaque
data:
  mongodb_connection_string: bW9uZ29kYjovL2FwcGxpY2F0aW9uOnBhc3N3b3JkQG1vbmdvZGItMC5tb25nb2RiLXN2Yy5tb25nb2RiLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3Lz9hdXRoU291cmNlPWFkbWluJmF1dGhNZWNoYW5pc209U0NSQU0tU0hBLTI1NiZyZWFkUHJlZmVyZW5jZT1zZWNvbmRhcnkmc3NsPWZhbHNlJmRpcmVjdENvbm5lY3Rpb249dHJ1ZQo=
