apiVersion: v1
kind: Service
metadata:
  name: nodejsapp-service
  namespace: app
  labels:
    app: nodejsapp-svc
spec:
  selector:
    app: nodejsapp
  type: ClusterIP
  ports:
    - targetPort: 3004
      port: 3080
      name: jasonbeh
