apiVersion: v1
kind: Service
metadata:
  name: nodejsapp-service
  namespace: app
spec:
  selector:
    app: nodejsapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3004
      nodePort: 31110
